---------------------------------------
-------------- DROP -------------------
---------------------------------------
-- SEQ
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_ADDRESS;
DROP SEQUENCE SEQ_STATUS;
DROP SEQUENCE SEQ_SELLER;
DROP SEQUENCE SEQ_CATEGORY;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_COLOR;
DROP SEQUENCE SEQ_PRODUCT_SIZE;
DROP SEQUENCE SEQ_INVENTORY;
DROP SEQUENCE SEQ_PRODUCT_IMG;
DROP SEQUENCE SEQ_FAVORITE;
DROP SEQUENCE SEQ_VIEW_HISTORY;
DROP SEQUENCE SEQ_REVIEW;
DROP SEQUENCE SEQ_CART;
DROP SEQUENCE SEQ_SEARCH_HISTORY;
DROP SEQUENCE SEQ_CARD_COMPANY;
DROP SEQUENCE SEQ_CARRIER;
DROP SEQUENCE SEQ_ORDERS;
DROP SEQUENCE SEQ_PAYMENT;
DROP SEQUENCE SEQ_ORDER_DETAIL;
DROP SEQUENCE SEQ_SHIPMENT;
DROP SEQUENCE SEQ_TRACKING_NO; -- FOR TRACKINGNO XX000000000
DROP SEQUENCE SEQ_ADMIN;
DROP SEQUENCE SEQ_ANNOUNCEMENT;
DROP SEQUENCE SEQ_FAQ_CATEGORY;
DROP SEQUENCE SEQ_FAQ;
DROP SEQUENCE SEQ_COUPON;
DROP SEQUENCE SEQ_COUPON_USAGE;
DROP SEQUENCE SEQ_REPORT;
DROP SEQUENCE SEQ_REPORT_IMG;
DROP SEQUENCE SEQ_REPORT_RESULT;
DROP SEQUENCE SEQ_PRODUCT_INQUIRY;
DROP SEQUENCE SEQ_ORDER_INQUIRY;


-- TABLE
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE STATUS CASCADE CONSTRAINTS;
DROP TABLE SELLER CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE COLOR CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_SIZE CASCADE CONSTRAINTS;
DROP TABLE INVENTORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_IMG CASCADE CONSTRAINTS;
DROP TABLE FAVORITE CASCADE CONSTRAINTS;
DROP TABLE VIEW_HISTORY CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE SEARCH_HISTORY CASCADE CONSTRAINTS;
DROP TABLE CARD_COMPANY CASCADE CONSTRAINTS;
DROP TABLE CARRIER CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE SHIPMENT CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE ANNOUNCEMENT CASCADE CONSTRAINTS;
DROP TABLE FAQ_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE FAQ CASCADE CONSTRAINTS;
DROP TABLE COUPON CASCADE CONSTRAINTS;
DROP TABLE COUPON_USAGE CASCADE CONSTRAINTS;
DROP TABLE REPORT CASCADE CONSTRAINTS;
DROP TABLE REPORT_IMG CASCADE CONSTRAINTS;
DROP TABLE REPORT_RESULT CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_INQUIRY CASCADE CONSTRAINTS;
DROP TABLE ORDER_INQUIRY CASCADE CONSTRAINTS;

---------------------------------------
-------------- SEQ --------------------
---------------------------------------
CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADDRESS NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STATUS NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SELLER NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COLOR NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT_SIZE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_INVENTORY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT_IMG NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FAVORITE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VIEW_HISTORY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REVIEW NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CART NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SEARCH_HISTORY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CARD_COMPANY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CARRIER NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDERS NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PAYMENT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER_DETAIL NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SHIPMENT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_TRACKING_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ADMIN NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANNOUNCEMENT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FAQ_CATEGORY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FAQ NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COUPON NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_COUPON_USAGE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPORT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPORT_IMG NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REPORT_RESULT NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT_INQUIRY NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER_INQUIRY NOCACHE NOCYCLE;

---------------------------------------
----------- CREATE TABLE --------------
---------------------------------------
-- MEMBER
CREATE TABLE MEMBER (
    MEMBER_NO NUMBER PRIMARY KEY
    , ID VARCHAR2(100) NOT NULL UNIQUE
    , PWD VARCHAR2(255) NOT NULL
    , NAME VARCHAR2(20) NOT NULL 
    , PHONE_NO VARCHAR2(11) NOT NULL
    , PREMIUM_YN CHAR(1) DEFAULT 'N' CHECK(PREMIUM_YN IN ('Y', 'N'))
    , DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N'))
    , CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL
    , BAN_DATE TIMESTAMP NULL
);


-- ADDRESS
CREATE TABLE ADDRESS (
    ADDRESS_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    POSTCODE VARCHAR2(10) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    DETAILED_ADDRESS VARCHAR2(200) NOT NULL,
    EXTRA_ADDRESS VARCHAR2(200),
    DEFAULT_YN CHAR(1) DEFAULT 'N' CHECK (DEFAULT_YN IN ('Y', 'N')),
    DEFAULT_REQ VARCHAR2(100) DEFAULT '조심히 와주세요~'
);


-- STATUS
CREATE TABLE STATUS (
    STATUS_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL
);


-- SELLER
CREATE TABLE SELLER (
    SELLER_NO NUMBER PRIMARY KEY,
    ACC_NAME VARCHAR2(90) NOT NULL UNIQUE,
    PWD VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK (DELETED_YN IN ('Y', 'N')) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE, 
    BANNER_IMG VARCHAR2(700) NULL,
    INFO VARCHAR2(400) NULL,
    SHIPPING_INFO VARCHAR2(200) NULL
);


-- CATEGORY
CREATE TABLE CATEGORY (
    CATEGORY_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL
);


-- PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_NO NUMBER PRIMARY KEY,
    SELLER_NO NUMBER NOT NULL,
    CATEGORY_NO NUMBER NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    DETAILS VARCHAR2(4000) NOT NULL,
    PRICE NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    EDITED_DATE TIMESTAMP NULL,
    HIT NUMBER DEFAULT 0,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N')) 
);


-- COLOR
CREATE TABLE COLOR (
    COLOR_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    HEXCODE VARCHAR2(10) NOT NULL
);


-- SIZE
CREATE TABLE PRODUCT_SIZE (
    SIZE_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(10) NOT NULL UNIQUE
);


-- INVENTORY
CREATE TABLE INVENTORY (
    INVENTORY_NO NUMBER PRIMARY KEY,
    PRODUCT_NO NUMBER NOT NULL,
    COLOR_NO NUMBER NOT NULL,
    SIZE_NO NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL
);


-- PRODUCT_IMG
CREATE TABLE PRODUCT_IMG (
    IMG_NO NUMBER PRIMARY KEY,
    PRODUCT_NO NUMBER NOT NULL,
    FILENAME VARCHAR2(500) NOT NULL,
    THUMBNAIL_YN CHAR(1) DEFAULT 'N' CHECK(THUMBNAIL_YN IN ('Y', 'N')),
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N')),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- FAVORITE
CREATE TABLE FAVORITE (
    FAVORITE_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- VIEW_HISTORY
CREATE TABLE VIEW_HISTORY (
    VIEW_HIST_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    VIEW_DATE TIMESTAMP DEFAULT SYSDATE
);

-- REVIEW
CREATE TABLE REVIEW (
    REVIEW_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    ORDERS_NO NUMBER NOT NULL,
    RATING NUMBER(10, 1) NOT NULL CHECK (RATING BETWEEN 1 AND 5 AND MOD(RATING * 10, 5) = 0),
    CONTENT VARCHAR2(2000) NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK (DELETED_YN IN ('Y', 'N')) NOT NULL
);


-- CART
CREATE TABLE CART (
    CART_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL CHECK (QUANTITY > 0),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- SEARCH_HISTORY
CREATE TABLE SEARCH_HISTORY (
    SEARCH_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    SEARCH_CONTENT VARCHAR2(255) NOT NULL,
    SEARCH_DATE TIMESTAMP DEFAULT SYSDATE
);


-- CARD_COMPANY
CREATE TABLE CARD_COMPANY (
    CARD_COMPANY_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL
);


-- CARRIER
CREATE TABLE CARRIER (
    CARRIER_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    CODE VARCHAR2(10) NOT NULL
);


-- ORDERS
CREATE TABLE ORDERS (
    ORDERS_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    ADDRESS_NO NUMBER NOT NULL,
    STATUS_NO NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    TOTAL_PRICE NUMBER NULL, -- TODO: CHECK LOGICAL ERRORS ON FE
    SHIPPING_REQ VARCHAR2(100) DEFAULT '부재 시 문 앞에 놓아주세요.' NULL,
    SHIPPING_FEE NUMBER DEFAULT 0 NOT NULL 
);

-- ORDER_DETAIL
CREATE TABLE ORDER_DETAIL (
    ORDER_DETAIL_NO NUMBER PRIMARY KEY,
    ORDERS_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    INVENTORY_NO NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL CHECK (QUANTITY > 0)
);

-- PAYMENT
CREATE TABLE PAYMENT (
    PAYMENT_NO NUMBER PRIMARY KEY,
    ORDERS_NO NUMBER NOT NULL,
    CARD_COMPANY_NO NUMBER NOT NULL,
    STATUS_NO NUMBER NOT NULL,
    PAYMENT_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    AMOUNT NUMBER NOT NULL
);


-- SHIPMENT
CREATE TABLE SHIPMENT (
    SHIPMENT_NO NUMBER PRIMARY KEY,
    ORDERS_NO NUMBER NOT NULL,
    STATUS_NO NUMBER NOT NULL,
    CARRIER_NO NUMBER NOT NULL,
    TRACKING_NO VARCHAR2(50) NOT NULL,
    SHIP_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    DELIVERY_DATE TIMESTAMP NULL
);


-- ADMIN
CREATE TABLE ADMIN (
    ADMIN_NO NUMBER PRIMARY KEY,
    ID VARCHAR2(90) NOT NULL UNIQUE,
    PWD VARCHAR2(255) NOT NULL,
    NICK VARCHAR2(30) NOT NULL UNIQUE,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK (DELETED_YN IN ('Y', 'N')),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- ANNOUNCEMENT
CREATE TABLE ANNOUNCEMENT (
    ANNOUNCEMENT_NO NUMBER PRIMARY KEY,
    ADMIN_NO NUMBER NOT NULL,
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N')),
    HIT NUMBER DEFAULT 0 NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- FAQ_CATEGORY
CREATE TABLE FAQ_CATEGORY (
    FAQ_CATEGORY_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL
);


-- FAQ
CREATE TABLE FAQ (
    FAQ_NO NUMBER PRIMARY KEY,
    ADMIN_NO NUMBER NOT NULL,
    FAQ_CATEGORY_NO NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N')),
    HIT NUMBER DEFAULT 0 NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- COUPON
CREATE TABLE COUPON (
    COUPON_NO NUMBER PRIMARY KEY,
    ADMIN_NO NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    CODE VARCHAR2(30) NOT NULL,
    DISCOUNT_PRICE NUMBER CHECK (DISCOUNT_PRICE > 0) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    EXPIRY_DATE TIMESTAMP NULL,
    USAGE_LIMIT NUMBER DEFAULT 500 NOT NULL 
);


-- COUPON_USAGE
CREATE TABLE COUPON_USAGE (
    COUPON_USAGE_NO NUMBER PRIMARY KEY,
    COUPON_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- REPORT 
CREATE TABLE REPORT (
    REPORT_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    TARGET_MEMBER_NO NUMBER NOT NULL,
    STATUS_NO NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- REPORT IMG
CREATE TABLE REPORT_IMG (
    REPORT_IMG_NO NUMBER PRIMARY KEY,
    REPORT_NO NUMBER NOT NULL,
    FILENAME VARCHAR2(500) NOT NULL
);


-- REPORT_RESULT
CREATE TABLE REPORT_RESULT (
    REPORT_RESULT_NO NUMBER PRIMARY KEY,
    ADMIN_NO NUMBER NOT NULL,
    REPORT_NO NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    BAN_DAYS NUMBER NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- PRODUCT INQUIRY
CREATE TABLE PRODUCT_INQUIRY (
    PRODUCT_INQUIRY_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    SELLER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    STATUS_NO NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    QUESTION_CONTENT VARCHAR2(4000) NOT NULL,
    RESPONSE_CONTENT VARCHAR2(4000) NULL,
    ASK_DATE TIMESTAMP DEFAULT SYSDATE,
    RESPONSE_DATE TIMESTAMP NULL,
    PRIVATE_YN CHAR(1) DEFAULT 'N' CHECK(PRIVATE_YN IN ('Y', 'N')) NOT NULL,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N')) NOT NULL
);


-- ORDER INQUIRY
CREATE TABLE ORDER_INQUIRY (
    ORDER_INQUIRY_NO NUMBER PRIMARY KEY,
    ORDERS_NO NUMBER NOT NULL,
    MEMBER_NO NUMBER NOT NULL,
    SELLER_NO NUMBER NOT NULL,
    STATUS_NO NUMBER NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    QUESTION_CONTENT VARCHAR2(4000) NOT NULL,
    RESPONSE_CONTENT VARCHAR2(4000) NULL,
    ASK_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    RESPONSE_DATE TIMESTAMP NULL
);

---------------------------------------
----------------- FK ------------------
---------------------------------------
-- ADDRESS
ALTER TABLE ADDRESS
ADD CONSTRAINT FK_ADDRESS_MEMBER_NO FOREIGN KEY (MEMBER_NO) 
REFERENCES MEMBER (MEMBER_NO);


-- PRODUCT
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_SELLER_NO FOREIGN KEY (SELLER_NO)
REFERENCES SELLER (SELLER_NO);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_CATEGORY_NO FOREIGN KEY (CATEGORY_NO)
REFERENCES CATEGORY (CATEGORY_NO);


-- INVENTORY
ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);

ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_COLOR_NO FOREIGN KEY (COLOR_NO)
REFERENCES COLOR (COLOR_NO);

ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_SIZE_NO FOREIGN KEY (SIZE_NO)
REFERENCES PRODUCT_SIZE (SIZE_NO);


-- PRODUCT_IMG
ALTER TABLE PRODUCT_IMG
ADD CONSTRAINT FK_PRODUCT_IMG_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);


-- FAVORITE
ALTER TABLE FAVORITE
ADD CONSTRAINT FK_FAVORITE_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE FAVORITE
ADD CONSTRAINT FK_FAVORITE_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);


-- VIEW_HISTORY
ALTER TABLE VIEW_HISTORY
ADD CONSTRAINT FK_VIEW_HISTORY_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE VIEW_HISTORY
ADD CONSTRAINT FK_VIEW_HISTORY_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);


-- REVIEW
ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_ORDERS_NO FOREIGN KEY (ORDERS_NO)
REFERENCES ORDERS (ORDERS_NO);

-- CART
ALTER TABLE CART
ADD CONSTRAINT FK_CART_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE CART
ADD CONSTRAINT FK_CART_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);


-- SEARCH_HISTORY
ALTER TABLE SEARCH_HISTORY
ADD CONSTRAINT FK_SEARCH_HISTORY_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);


-- ORDERS
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_ADDRESS_NO FOREIGN KEY (ADDRESS_NO)
REFERENCES ADDRESS (ADDRESS_NO);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_STATUS_NO FOREIGN KEY (STATUS_NO)
REFERENCES STATUS (STATUS_NO);


-- PAYMENT
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_ORDERS_NO FOREIGN KEY (ORDERS_NO)
REFERENCES ORDERS (ORDERS_NO);

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_CARD_COMPANY_NO FOREIGN KEY (CARD_COMPANY_NO)
REFERENCES CARD_COMPANY (CARD_COMPANY_NO);

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_STATUS_NO FOREIGN KEY (STATUS_NO)
REFERENCES STATUS (STATUS_NO);


-- ORDER_DETAIL
ALTER TABLE ORDER_DETAIL
ADD CONSTRAINT FK_ORDER_DETAIL_ORDERS_NO FOREIGN KEY (ORDERS_NO)
REFERENCES ORDERS (ORDERS_NO);

ALTER TABLE ORDER_DETAIL
ADD CONSTRAINT FK_ORDER_DETAIL_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);

ALTER TABLE ORDER_DETAIL
ADD CONSTRAINT FK_ORDER_DETAIL_INVENTORY_NO FOREIGN KEY (INVENTORY_NO)
REFERENCES INVENTORY (INVENTORY_NO);


-- SHIPMENT
ALTER TABLE SHIPMENT
ADD CONSTRAINT FK_SHIPMENT_ORDERS_NO FOREIGN KEY (ORDERS_NO)
REFERENCES ORDERS (ORDERS_NO);

ALTER TABLE SHIPMENT
ADD CONSTRAINT FK_SHIPMENT_STATUS_NO FOREIGN KEY (STATUS_NO)
REFERENCES STATUS (STATUS_NO);

ALTER TABLE SHIPMENT
ADD CONSTRAINT FK_SHIPMENT_CARRIER_NO FOREIGN KEY (CARRIER_NO)
REFERENCES CARRIER (CARRIER_NO);


-- ANNOUNCEMENT
ALTER TABLE ANNOUNCEMENT
ADD CONSTRAINT FK_ANNOUNCEMENT_ADMIN_NO FOREIGN KEY (ADMIN_NO)
REFERENCES ADMIN (ADMIN_NO);


-- FAQ
ALTER TABLE FAQ
ADD CONSTRAINT FK_FAQ_ADMIN_NO FOREIGN KEY (ADMIN_NO)
REFERENCES ADMIN (ADMIN_NO);

ALTER TABLE FAQ
ADD CONSTRAINT FK_FAQ_FAQ_CATEGORY_NO FOREIGN KEY (FAQ_CATEGORY_NO)
REFERENCES FAQ_CATEGORY (FAQ_CATEGORY_NO);


-- COUPON
ALTER TABLE COUPON
ADD CONSTRAINT FK_COUPON_ADMIN_NO FOREIGN KEY (ADMIN_NO)
REFERENCES ADMIN (ADMIN_NO);


-- COUPON_USAGE 
ALTER TABLE COUPON_USAGE
ADD CONSTRAINT FK_COUPON_USAGE_COUPON_NO FOREIGN KEY (COUPON_NO)
REFERENCES COUPON (COUPON_NO);


-- REPORT
ALTER TABLE REPORT
ADD CONSTRAINT FK_REPORT_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE REPORT
ADD CONSTRAINT FK_REPORT_TARGET_MEMBER_NO FOREIGN KEY (TARGET_MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE REPORT
ADD CONSTRAINT FK_REPORT_STATUS_NO FOREIGN KEY (STATUS_NO)
REFERENCES STATUS (STATUS_NO);


-- REPORT_IMG
ALTER TABLE REPORT_IMG
ADD CONSTRAINT FK_REPORT_IMG_REPORT_NO FOREIGN KEY (REPORT_NO)
REFERENCES REPORT (REPORT_NO);


-- REPORT_RESULT
ALTER TABLE REPORT_RESULT
ADD CONSTRAINT FK_REPORT_RESULT_ADMIN_NO FOREIGN KEY (ADMIN_NO)
REFERENCES ADMIN (ADMIN_NO);

ALTER TABLE REPORT_RESULT
ADD CONSTRAINT FK_REPORT_RESULT_REPORT_NO FOREIGN KEY (REPORT_NO)
REFERENCES REPORT (REPORT_NO);


-- PRODUCT_INQUIRY
ALTER TABLE PRODUCT_INQUIRY
ADD CONSTRAINT FK_PRODUCT_INQUIRY_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE PRODUCT_INQUIRY
ADD CONSTRAINT FK_PRODUCT_INQUIRY_SELLER_NO FOREIGN KEY (SELLER_NO)
REFERENCES SELLER (SELLER_NO);

ALTER TABLE PRODUCT_INQUIRY
ADD CONSTRAINT FK_PRODUCT_INQUIRY_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);

ALTER TABLE PRODUCT_INQUIRY
ADD CONSTRAINT FK_PRODUCT_INQUIRY_STATUS_NO FOREIGN KEY (STATUS_NO)
REFERENCES STATUS (STATUS_NO);


-- ORDER_INQUIRY
ALTER TABLE ORDER_INQUIRY
ADD CONSTRAINT FK_ORDER_INQUIRY_ORDERS_NO FOREIGN KEY (ORDERS_NO)
REFERENCES ORDERS (ORDERS_NO);

ALTER TABLE ORDER_INQUIRY
ADD CONSTRAINT FK_ORDER_INQUIRY_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE ORDER_INQUIRY
ADD CONSTRAINT FK_ORDER_INQUIRY_SELLER_NO FOREIGN KEY (SELLER_NO)
REFERENCES SELLER (SELLER_NO);

ALTER TABLE ORDER_INQUIRY
ADD CONSTRAINT FK_ORDER_INQUIRY_STATUS_NO FOREIGN KEY (STATUS_NO)
REFERENCES STATUS (STATUS_NO);




---------------------------------------
------------- INSERT ------------------
---------------------------------------
-- MEMBER
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES(SEQ_MEMBER.NEXTVAL, 'USER01@gmail.com', '1234', '김태우', '01036207737');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER02@gmail.com', '1234', '이민호', '01012345678');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER03@gmail.com', '1234', '박지성', '01023456789');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER04@gmail.com', '1234', '손흥민', '01034567890');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER05@gmail.com', '1234', '김연아', '01045678901');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER06@gmail.com', '1234', '정우성', '01056789012');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER07@gmail.com', '1234', '하정우', '01067890123');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER08@gmail.com', '1234', '공유', '01078901234');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER09@gmail.com', '1234', '이영애', '01089012345');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER10@gmail.com', '1234', '배수지', '01090123456');
COMMIT;


-- ADDRESS
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 1, '10416', '기흥역로 16', '2530동 202호', '(기흥동 15번지)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 1, '12345', '강남역', '2번출구', '(3번 출구사이)'); 
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 2, '10516', '서울특별시 강남구', '삼성로 1', '(삼성동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 3, '10617', '서울특별시 강북구', '도봉로 2', '(도봉동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 4, '10718', '서울특별시 서초구', '서초로 3', '(서초동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 5, '10819', '서울특별시 송파구', '송파로 4', '(송파동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 6, '10920', '서울특별시 마포구', '마포로 5', '(마포동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 7, '11021', '서울특별시 은평구', '은평로 6', '(은평동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 8, '11122', '서울특별시 동작구', '동작로 7', '(동작동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 9, '11223', '서울특별시 강서구', '강서로 8', '(강서동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 10, '11324', '서울특별시 구로구', '구로로 9', '(구로동)');
COMMIT;


-- STATUS
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '입금/결제');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '배송준비중');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '배송중');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '배송완료');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '취소');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '보류');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '완료');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '실패');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '처리중');
INSERT INTO STATUS (STATUS_NO, NAME) VALUES (SEQ_STATUS.NEXTVAL, '문의 접수');
INSERT INTO STATUS (STATUS_NO, NAME) VALUES (SEQ_STATUS.NEXTVAL, '답변 완료');
COMMIT;


-- SELLER
INSERT INTO SELLER(SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller01@gmail.com', '1234', '노스페이스', 'banner-img.jpg', '저희 노스페이스는 너무나 아름다운 브랜드입니다.', '노스페이스는 설 연휴간 (3/10~3/13) 배송이 되지 않습니다.');
INSERT INTO SELLER(SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller02@gmail.com', '1234', '퓨마', 'banner-img-puma.jpg', '저희 퓨마는 너무나 아름다운 브랜드입니다.');
INSERT INTO SELLER(SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller03@gmail.com', '1234', '나이키', 'banner-img.jpg', '저희 나이키는 너무나 아름다운 브랜드입니다.','나이키는 설 연휴간 (3/10~3/13) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller04@gmail.com', '1234', '아디다스', 'banner-img-adidas.jpg', '저희 아디다스는 혁신적인 브랜드입니다.', '아디다스는 명절간 (2/8~2/10) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller05@gmail.com', '1234', '리복', 'banner-img-reebok.jpg', '저희 리복은 최고의 품질을 자랑합니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller06@gmail.com', '1234', '뉴발란스', 'banner-img-newbalance.jpg', '저희 뉴발란스는 편안함을 제공합니다.', '뉴발란스는 주말간 (3/5~3/6) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller07@gmail.com', '1234', '언더아머', 'banner-img-underarmour.jpg', '저희 언더아머는 최고의 퍼포먼스를 제공합니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller08@gmail.com', '1234', '콜롬비아', 'banner-img-columbia.jpg', '저희 콜롬비아는 최고의 등산복을 제공합니다.', '콜롬비아는 명절간 (1/1~1/2) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller09@gmail.com', '1234', '빈폴', 'banner-img-beanpole.jpg', '저희 빈폴은 클래식한 패션을 제공합니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller10@gmail.com', '1234', '캘빈클라인', 'banner-img-ck.jpg', '저희 캘빈클라인은 스타일리시한 데님을 제공합니다.', '캘빈클라인은 연말연시간 (12/31~1/1) 배송이 되지 않습니다.');
COMMIT;


-- CATEGORY
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '상의');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '하의');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '모자');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '아우터');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '신발');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '스니커즈');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '가방');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '액세서리');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '기타');
COMMIT;


-- PRODUCT
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 1, 4, '노스페이스 자켓', '노스페이스 자켓 설명', 199900);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 2, 4, '퓨마 윈드브레이커', '윈드브레이커 냠냠구냠냠구 설명', 49900);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 3, 5, '나이키 짱짱한 운동화', '나이키 운동화 냠냠구냠냠구 냠냠구냠냠구 냠냠구냠냠구 설명', 2400900);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 1, 3, '노스페이스 모자', '노스페이스 모자 설명', 39000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 2, 6, '퓨마 스니커즈', '퓨마 스니커즈 설명', 99000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 3, 2, '나이키 팬츠', '나이키 팬츠 설명', 89000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 4, 1, '아디다스 티셔츠', '아디다스 티셔츠 설명', 45000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 4, 4, '아디다스 자켓', '아디다스 자켓 설명', 120000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 5, 2, '리복 팬츠', '리복 팬츠 설명', 69000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 5, 6, '리복 스니커즈', '리복 스니커즈 설명', 110000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 6, 5, '뉴발란스 운동화', '뉴발란스 운동화 설명', 99000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 6, 4, '뉴발란스 자켓', '뉴발란스 자켓 설명', 150000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 7, 1, '언더아머 티셔츠', '언더아머 티셔츠 설명', 55000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 7, 2, '언더아머 팬츠', '언더아머 팬츠 설명', 65000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 8, 8, '콜롬비아 모자', '콜롬비아 모자 설명', 30000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 8, 7, '콜롬비아 가방', '콜롬비아 가방 설명', 85000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 9, 1, '빈폴 셔츠', '빈폴 셔츠 설명', 70000.65);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 9, 4, '빈폴 자켓', '빈폴 자켓 설명', 170000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 10, 2, '캘빈클라인 팬츠', '캘빈클라인 팬츠 설명', 90000);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 10, 3, '캘빈클라인 모자', '캘빈클라인 모자 설명', 40000);
COMMIT;


-- COLOR
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '빨강', '#FF0000');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '초록', '#00FF00');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '파랑', '#0000FF');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '노랑', '#FFFF00');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '청록', '#00FFFF');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '자홍', '#FF00FF');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '검정', '#000000');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '흰색', '#FFFFFF');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '회색', '#808080');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '주황', '#FFA500');
COMMIT;


-- SIZE
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'S');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'M');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'L');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'XL');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'XLL');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'XLLL');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'FREE');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '225');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '230');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '235');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '240');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '245');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '250');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '255');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '260');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '265');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '270');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '275');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '280');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '285');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '290');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '295');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '300');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '305');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '310');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '320');
COMMIT;

-- INVENTORY
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 1, 1, 1, 100);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 1, 2, 2, 150);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 2, 3, 3, 200);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 2, 4, 4, 250);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 3, 5, 5, 300);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 3, 6, 6, 350);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 4, 7, 7, 400);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 4, 8, 8, 450);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 5, 9, 9, 500);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 5, 10, 10, 550);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 6, 1, 11, 600);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 6, 2, 12, 650);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 7, 3, 13, 700);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 7, 4, 14, 750);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 8, 5, 15, 800);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 8, 6, 16, 850);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 9, 7, 17, 900);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 9, 8, 18, 950);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 10, 9, 19, 1000);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 10, 10, 20, 1050);
COMMIT;


-- PRODUCT_IMG
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 1, 'img-1.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 1, 'img-2.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 2, 'img-3.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 2, 'img-4.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 3, 'img-5.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 3, 'img-6.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 4, 'img-7.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 4, 'img-8.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 5, 'img-9.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 5, 'img-10.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 6, 'img-11.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 6, 'img-12.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 7, 'img-13.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 7, 'img-14.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 8, 'img-15.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 8, 'img-16.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 9, 'img-17.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 9, 'img-18.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 10, 'img-19.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 10, 'img-20.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 11, 'img-21.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 11, 'img-22.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 12, 'img-23.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 12, 'img-24.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 13, 'img-25.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 14, 'img-26.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 15, 'img-27.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 16, 'img-28.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 17, 'img-29.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 18, 'img-30.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 19, 'img-31.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 20, 'img-32.jpg', 'Y');
COMMIT;


-- FAVORITE
INSERT INTO FAVORITE(FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 1, 1, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 1, 2, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 1, 3, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 2, 4, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 2, 5, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 2, 6, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 3, 7, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 3, 8, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 3, 9, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 4, 10, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 4, 1, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 4, 2, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 5, 3, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 5, 4, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 5, 5, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 6, 6, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 6, 7, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 6, 8, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 7, 9, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 7, 10, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 7, 1, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 8, 2, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 8, 3, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 8, 4, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 9, 5, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 9, 6, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 9, 7, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 10, 8, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 10, 9, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 10, 10, SYSDATE);
COMMIT;


-- VIEW_HISTORY
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 1, 1, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 1, 2, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 1, 3, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 2, 4, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 2, 5, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 2, 6, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 3, 7, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 3, 8, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 3, 9, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 4, 10, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 4, 1, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 4, 2, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 5, 3, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 5, 4, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 5, 5, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 6, 6, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 6, 7, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 6, 8, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 7, 9, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 7, 10, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 7, 1, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 8, 2, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 8, 3, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 8, 4, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 9, 5, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 9, 6, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 9, 7, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 10, 8, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 10, 9, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 10, 10, SYSDATE);
COMMIT;




-- CART
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 1, 1, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 1, 2, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 1, 3, 3, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 2, 4, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 2, 5, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 2, 6, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 3, 7, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 3, 8, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 3, 9, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 4, 10, 3, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 4, 1, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 4, 2, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 5, 3, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 5, 4, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 5, 5, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 6, 6, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 6, 7, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 6, 8, 3, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 7, 9, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 7, 10, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 7, 1, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 8, 2, 3, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 8, 3, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 8, 4, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 9, 5, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 9, 6, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 9, 7, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 10, 8, 2, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 10, 9, 1, SYSDATE);
INSERT INTO CART (CART_NO, MEMBER_NO, PRODUCT_NO, QUANTITY, CREATED_DATE) VALUES (SEQ_CART.NEXTVAL, 10, 10, 3, SYSDATE);
COMMIT;


-- SEARCH_HISTORY
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 1, '자켓', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 1, '운동화', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 1, '윈드브레이커', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 2, '팬츠', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 2, '나이키', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 2, '캘빈클라인', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 3, '티셔츠', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 3, '뉴발란스', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 3, '모자', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 4, '셔츠', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 4, '리복', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 4, '운동화', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 5, '모자', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 5, '아디다스', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 5, '캘빈클라인', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 6, '콜롬비아', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 6, '빈폴', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 6, '뉴발란스', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 7, '팬츠', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 7, '팬츠', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 7, '퓨마', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 8, '아디다스', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 8, '리복', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 8, '캘빈클라인', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 9, '자켓', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 9, '신발', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 9, '아디다스', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 10, '캘빈클라인', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 10, '뉴발란스', SYSDATE);
INSERT INTO SEARCH_HISTORY (SEARCH_NO, MEMBER_NO, SEARCH_CONTENT, SEARCH_DATE) VALUES (SEQ_SEARCH_HISTORY.NEXTVAL, 10, '언더아머', SYSDATE);
COMMIT;


-- CARD_COMPANY
INSERT INTO CARD_COMPANY (CARD_COMPANY_NO, NAME) VALUES (SEQ_CARD_COMPANY.NEXTVAL, 'Visa');
INSERT INTO CARD_COMPANY (CARD_COMPANY_NO, NAME) VALUES (SEQ_CARD_COMPANY.NEXTVAL, 'MasterCard');
INSERT INTO CARD_COMPANY (CARD_COMPANY_NO, NAME) VALUES (SEQ_CARD_COMPANY.NEXTVAL, 'American Express');
INSERT INTO CARD_COMPANY (CARD_COMPANY_NO, NAME) VALUES (SEQ_CARD_COMPANY.NEXTVAL, 'UnionPay');
INSERT INTO CARD_COMPANY (CARD_COMPANY_NO, NAME) VALUES (SEQ_CARD_COMPANY.NEXTVAL, 'Korean Card');
INSERT INTO CARD_COMPANY (CARD_COMPANY_NO, NAME) VALUES (SEQ_CARD_COMPANY.NEXTVAL, 'Samsung Card');
INSERT INTO CARD_COMPANY (CARD_COMPANY_NO, NAME) VALUES (SEQ_CARD_COMPANY.NEXTVAL, 'Hyundai Card');
INSERT INTO CARD_COMPANY (CARD_COMPANY_NO, NAME) VALUES (SEQ_CARD_COMPANY.NEXTVAL, 'Shinhan Card');
COMMIT;


-- CARRIER
INSERT INTO CARRIER (CARRIER_NO, NAME, CODE) VALUES (SEQ_CARRIER.NEXTVAL, 'FedEx', 'FX');
INSERT INTO CARRIER (CARRIER_NO, NAME, CODE) VALUES (SEQ_CARRIER.NEXTVAL, 'DHL', 'DH');
INSERT INTO CARRIER (CARRIER_NO, NAME, CODE) VALUES (SEQ_CARRIER.NEXTVAL, 'UPS', 'UP');
INSERT INTO CARRIER (CARRIER_NO, NAME, CODE) VALUES (SEQ_CARRIER.NEXTVAL, 'USPS', 'US');
INSERT INTO CARRIER (CARRIER_NO, NAME, CODE) VALUES (SEQ_CARRIER.NEXTVAL, 'TNT', 'TN');
INSERT INTO CARRIER (CARRIER_NO, NAME, CODE) VALUES (SEQ_CARRIER.NEXTVAL, 'Korea Post', 'KP');
INSERT INTO CARRIER (CARRIER_NO, NAME, CODE) VALUES (SEQ_CARRIER.NEXTVAL, 'CJ Logistics', 'CJ');
INSERT INTO CARRIER (CARRIER_NO, NAME, CODE) VALUES (SEQ_CARRIER.NEXTVAL, 'Hanjin Express', 'HJ');
COMMIT;


-- ORDERS
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 1, 1, 1, 199900, 5000, '부재 시 문 앞에 놓아주세요.');
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 1, 2, 2, 49900, 3000, '부재 시 경비실에 맡겨주세요.');
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 2, 3, 3, 2400900, 7000, '부재 시 문 앞에 놓아주세요.');
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 3, 4, 4, 39000, 2000, '부재 시 문 앞에 놓아주세요.');
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 4, 5, 5, 99000, 3000, '부재 시 문 앞에 놓아주세요.');
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 5, 6, 6, 89000, 4000, '부재 시 문 앞에 놓아주세요.');
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 6, 7, 7, 45000, 2000, '부재 시 문 앞에 놓아주세요.');
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 7, 8, 8, 120000, 5000, '부재 시 문 앞에 놓아주세요.');
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 8, 9, 1, 69000, 3000, '부재 시 문 앞에 놓아주세요.');
INSERT INTO ORDERS (ORDERS_NO, MEMBER_NO, ADDRESS_NO, STATUS_NO, TOTAL_PRICE, SHIPPING_FEE, SHIPPING_REQ) VALUES (SEQ_ORDERS.NEXTVAL, 9, 10, 2, 110000, 4000, '부재 시 문 앞에 놓아주세요.');
COMMIT;


-- ORDER_DETAIL
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 1, 1, 1, 2);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 1, 2, 2, 1);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 2, 3, 3, 3);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 3, 4, 4, 1);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 4, 5, 5, 4);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 5, 6, 6, 2);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 6, 7, 7, 1);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 7, 8, 8, 3);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 8, 9, 9, 1);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 9, 10, 10, 2);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 10, 1, 11, 3);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 10, 2, 12, 1);
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_NO, ORDERS_NO, PRODUCT_NO, INVENTORY_NO, QUANTITY) VALUES (SEQ_ORDER_DETAIL.NEXTVAL, 10, 3, 13, 4);
COMMIT;



-- REVIEW
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 1, 1, 4.5, '정말 따뜻하고 좋아요!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 1, 2, 3.5, '가볍고 편해요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 1, 3, 5.0, '최고에요!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 2, 4, 4.0, '디자인이 예뻐요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 2, 5, 4.5, '너무 편해요!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 2, 6, 4.0, '품질이 좋네요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 3, 7, 4.5, '강추!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 3, 8, 4.0, '아주 좋아요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 3, 9, 4.5, '아주 멋있어요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 4, 10, 4.5, '정말 편안해요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 4, 1, 4.0, '정말 따뜻하고 좋아요!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 4, 2, 3.5, '가볍고 편해요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 5, 3, 5.0, '최고에요!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 5, 4, 4.0, '디자인이 예뻐요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 5, 5, 4.5, '너무 편해요!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 6, 6, 4.0, '품질이 좋네요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 6, 7, 4.5, '강추!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 6, 8, 4.0, '아주 좋아요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 7, 9, 4.5, '아주 멋있어요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 7, 10, 4.5, '정말 편안해요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 7, 1, 4.0, '정말 따뜻하고 좋아요!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 8, 2, 3.5, '가볍고 편해요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 8, 3, 5.0, '최고에요!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 8, 4, 4.0, '디자인이 예뻐요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 9, 5, 4.5, '너무 편해요!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 9, 6, 4.0, '품질이 좋네요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 9, 7, 4.5, '강추!', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 10, 8, 4.0, '아주 좋아요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 10, 9, 4.5, '아주 멋있어요.', SYSDATE);
--INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 10, 10, 4.5, '정말 편안해요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 1, 1, 1, 4.5, '정말 따뜻하고 좋아요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 1, 2, 1, 3.5, '가볍고 편해요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 2, 3, 2, 5.0, '최고에요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 2, 4, 3, 4.0, '디자인이 예뻐요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 3, 5, 4, 4.5, '너무 편해요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 3, 6, 5, 4.0, '품질이 좋네요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 4, 7, 6, 4.5, '강추!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 4, 8, 7, 4.0, '아주 좋아요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 5, 9, 8, 4.5, '아주 멋있어요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 5, 10, 9, 4.5, '정말 편안해요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 6, 1, 10, 4.0, '정말 따뜻하고 좋아요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 6, 2, 1, 3.5, '가볍고 편해요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 7, 3, 2, 5.0, '최고에요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 7, 4, 3, 4.0, '디자인이 예뻐요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 8, 5, 4, 4.5, '너무 편해요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 8, 6, 5, 4.0, '품질이 좋네요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 9, 7, 6, 4.5, '강추!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 9, 8, 7, 4.0, '아주 좋아요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 10, 9, 8, 4.5, '아주 멋있어요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, ORDERS_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 10, 10, 9, 4.5, '정말 편안해요.', SYSDATE);

COMMIT;


-- PAYMENT
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 1, 1, 1, 199900);
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 2, 2, 1, 49900);
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 3, 3, 1, 2400900);
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 4, 4, 1, 39000);
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 5, 5, 1, 99000);
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 6, 6, 1, 89000);
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 7, 7, 1, 45000);
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 8, 8, 1, 120000);
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 9, 1, 1, 69000);
INSERT INTO PAYMENT (PAYMENT_NO, ORDERS_NO, CARD_COMPANY_NO, STATUS_NO, AMOUNT) VALUES (SEQ_PAYMENT.NEXTVAL, 10, 2, 1, 110000);
COMMIT;


-- SHIPMENT
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 1, 3, 1, 'FX' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE);
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 2, 2, 2, 'DH' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE);
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 3, 2, 3, 'UP' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE);
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE, DELIVERY_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 4, 4, 4, 'US' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE, SYSDATE + 3);
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 5, 3, 5, 'TN' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE);
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 6, 2, 6, 'KP' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE);
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 7, 2, 7, 'CJ' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE);
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 8, 3, 8, 'HJ' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE);
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 9, 2, 1, 'FX' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE);
INSERT INTO SHIPMENT (SHIPMENT_NO, ORDERS_NO, STATUS_NO, CARRIER_NO, TRACKING_NO, SHIP_DATE, DELIVERY_DATE) VALUES (SEQ_SHIPMENT.NEXTVAL, 10, 4, 2, 'DH' || LPAD(SEQ_TRACKING_NO.NEXTVAL, 9, '0'), SYSDATE, SYSDATE + 5);
COMMIT;


-- ADMIN
INSERT INTO ADMIN (ADMIN_NO, ID, PWD, NICK) VALUES (SEQ_ADMIN.NEXTVAL, 'admin1@example.com', 'password123', 'admin1');
INSERT INTO ADMIN (ADMIN_NO, ID, PWD, NICK) VALUES (SEQ_ADMIN.NEXTVAL, 'admin2@example.com', 'password123', 'admin2');
INSERT INTO ADMIN (ADMIN_NO, ID, PWD, NICK) VALUES (SEQ_ADMIN.NEXTVAL, 'admin3@example.com', 'password123', 'admin3');
INSERT INTO ADMIN (ADMIN_NO, ID, PWD, NICK) VALUES (SEQ_ADMIN.NEXTVAL, 'admin4@example.com', 'password123', 'admin4');
INSERT INTO ADMIN (ADMIN_NO, ID, PWD, NICK) VALUES (SEQ_ADMIN.NEXTVAL, 'admin5@example.com', 'password123', 'admin5');
COMMIT;


-- ANNOUNCEMENT
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, ADMIN_NO, TITLE, CONTENT) VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 1, '시스템 유지보수', '시스템 유지보수를 2시부터 4시까지 진행할 예정입니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, ADMIN_NO, TITLE, CONTENT) VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 2, '새로운 기능 추가', '새로운 사용자 대시보드를 포함한 여러 기능이 추가되었습니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, ADMIN_NO, TITLE, CONTENT) VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 3, '휴일 공지', '12월 24일부터 1월 2일까지 휴무입니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, ADMIN_NO, TITLE, CONTENT) VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 4, '보안 업데이트', '데이터 보호를 위한 새로운 보안 조치가 시행되었습니다.');
INSERT INTO ANNOUNCEMENT (ANNOUNCEMENT_NO, ADMIN_NO, TITLE, CONTENT) VALUES (SEQ_ANNOUNCEMENT.NEXTVAL, 5, '고객 지원 안내', '고객 지원 시간이 9시부터 21시로 변경되었습니다.');
COMMIT;


-- FAQ_CATEGORY
INSERT INTO FAQ_CATEGORY (FAQ_CATEGORY_NO, NAME) VALUES (SEQ_FAQ_CATEGORY.NEXTVAL, '배송');
INSERT INTO FAQ_CATEGORY (FAQ_CATEGORY_NO, NAME) VALUES (SEQ_FAQ_CATEGORY.NEXTVAL, '결제');
INSERT INTO FAQ_CATEGORY (FAQ_CATEGORY_NO, NAME) VALUES (SEQ_FAQ_CATEGORY.NEXTVAL, '환불');
INSERT INTO FAQ_CATEGORY (FAQ_CATEGORY_NO, NAME) VALUES (SEQ_FAQ_CATEGORY.NEXTVAL, '회원가입');
INSERT INTO FAQ_CATEGORY (FAQ_CATEGORY_NO, NAME) VALUES (SEQ_FAQ_CATEGORY.NEXTVAL, '계정');
COMMIT;


-- FAQ
INSERT INTO FAQ (FAQ_NO, ADMIN_NO, FAQ_CATEGORY_NO, TITLE, CONTENT) VALUES (SEQ_FAQ.NEXTVAL, 1, 1, '배송 소요 시간은 얼마나 걸리나요?', '주문 후 배송까지 평균적으로 3-5일이 소요됩니다.');
INSERT INTO FAQ (FAQ_NO, ADMIN_NO, FAQ_CATEGORY_NO, TITLE, CONTENT) VALUES (SEQ_FAQ.NEXTVAL, 2, 2, '결제 시 오류가 발생하면 어떻게 해야 하나요?', '결제 시 오류가 발생하면 고객센터에 문의해주시기 바랍니다.');
INSERT INTO FAQ (FAQ_NO, ADMIN_NO, FAQ_CATEGORY_NO, TITLE, CONTENT) VALUES (SEQ_FAQ.NEXTVAL, 3, 3, '환불을 신청하려면 어떻게 해야 하나요?', '환불을 신청하려면 주문 내역에서 환불 요청 버튼을 눌러주세요.');
INSERT INTO FAQ (FAQ_NO, ADMIN_NO, FAQ_CATEGORY_NO, TITLE, CONTENT) VALUES (SEQ_FAQ.NEXTVAL, 4, 4, '회원가입은 어떻게 하나요?', '회원가입은 홈페이지 상단의 회원가입 버튼을 클릭하고 양식을 작성하시면 됩니다.');
INSERT INTO FAQ (FAQ_NO, ADMIN_NO, FAQ_CATEGORY_NO, TITLE, CONTENT) VALUES (SEQ_FAQ.NEXTVAL, 5, 5, '계정이 잠겼을 때 어떻게 풀 수 있나요?', '계정이 잠겼을 때는 고객센터에 연락하여 계정 잠금을 해제할 수 있습니다.');
COMMIT;



-- COUPON
INSERT INTO COUPON (COUPON_NO, ADMIN_NO, NAME, CODE, DISCOUNT_PRICE, EXPIRY_DATE) VALUES (SEQ_COUPON.NEXTVAL, 1, '신규 가입 할인', 'NEWJOIN10', 10000, TO_TIMESTAMP('2024-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COUPON (COUPON_NO, ADMIN_NO, NAME, CODE, DISCOUNT_PRICE, EXPIRY_DATE) VALUES (SEQ_COUPON.NEXTVAL, 2, '블랙 프라이데이 할인', 'BLACKFRI20', 20000, TO_TIMESTAMP('2024-11-25 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COUPON (COUPON_NO, ADMIN_NO, NAME, CODE, DISCOUNT_PRICE, EXPIRY_DATE) VALUES (SEQ_COUPON.NEXTVAL, 3, '여름 세일', 'SUMMER15', 15000, TO_TIMESTAMP('2024-08-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COUPON (COUPON_NO, ADMIN_NO, NAME, CODE, DISCOUNT_PRICE, EXPIRY_DATE) VALUES (SEQ_COUPON.NEXTVAL, 4, '겨울 특별 할인', 'WINTER25', 25000, TO_TIMESTAMP('2024-12-31 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO COUPON (COUPON_NO, ADMIN_NO, NAME, CODE, DISCOUNT_PRICE, EXPIRY_DATE) VALUES (SEQ_COUPON.NEXTVAL, 5, '추석 할인', 'CHUSEOK10', 10000, TO_TIMESTAMP('2024-09-30 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
COMMIT;


-- COUPON_USAGE
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 1, 1);
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 2, 2);
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 3, 3);
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 4, 4);
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 5, 5);
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 1, 6);
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 2, 7);
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 3, 8);
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 4, 9);
INSERT INTO COUPON_USAGE (COUPON_USAGE_NO, COUPON_NO, MEMBER_NO) VALUES (SEQ_COUPON_USAGE.NEXTVAL, 5, 10);
COMMIT;


-- REPORT
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 1, 2, 9, '부적절한 언어 사용', '회원이 채팅 중 부적절한 언어를 사용했습니다.');
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 2, 3, 9, '스팸 메시지', '회원이 스팸 메시지를 반복적으로 보냅니다.');
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 3, 4, 9, '허위 정보 제공', '회원이 허위 정보를 제공하고 있습니다.');
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 4, 5, 9, '악의적인 비방', '회원이 악의적인 비방을 하고 있습니다.');
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 5, 6, 9, '사기 행위', '회원이 사기 행위를 시도하고 있습니다.');
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 6, 7, 9, '지속적인 괴롭힘', '회원이 지속적으로 괴롭히고 있습니다.');
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 7, 8, 9, '부적절한 이미지 업로드', '회원이 부적절한 이미지를 업로드했습니다.');
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 8, 9, 9, '허위 리뷰 작성', '회원이 허위 리뷰를 작성했습니다.');
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 9, 10, 9, '협박 및 위협', '회원이 협박 및 위협을 하고 있습니다.');
INSERT INTO REPORT (REPORT_NO, MEMBER_NO, TARGET_MEMBER_NO, STATUS_NO, TITLE, CONTENT) VALUES (SEQ_REPORT.NEXTVAL, 10, 1, 9, '기타', '기타 부적절한 행위가 발생했습니다.');
COMMIT;


-- REPORT_IMG
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 1, 'img-1.jpg');
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 2, 'img-2.jpg');
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 3, 'img-3.jpg');
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 4, 'img-4.jpg');
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 5, 'img-5.jpg');
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 6, 'img-6.jpg');
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 7, 'img-7.jpg');
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 8, 'img-8.jpg');
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 9, 'img-9.jpg');
INSERT INTO REPORT_IMG (REPORT_IMG_NO, REPORT_NO, FILENAME) VALUES (SEQ_REPORT_IMG.NEXTVAL, 10, 'img-10.jpg');
COMMIT;


-- REPORT_RESULT
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 1, 1, '처리 완료', '회원이 부적절한 언어를 사용한 것이 확인되어 경고 조치하였습니다.', NULL);
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 2, 2, '처리 완료', '회원이 스팸 메시지를 반복적으로 보내어 계정을 7일간 정지하였습니다.', 7);
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 3, 3, '처리 완료', '회원이 허위 정보를 제공한 것이 확인되어 계정을 3일간 정지하였습니다.', 3);
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 4, 4, '처리 완료', '회원이 악의적인 비방을 한 것이 확인되어 경고 조치하였습니다.', NULL);
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 5, 5, '처리 완료', '회원이 사기 행위를 시도한 것이 확인되어 계정을 영구 정지하였습니다.', NULL);
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 1, 6, '처리 완료', '회원이 지속적으로 괴롭힘을 한 것이 확인되어 계정을 14일간 정지하였습니다.', 14);
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 2, 7, '처리 완료', '회원이 부적절한 이미지를 업로드한 것이 확인되어 경고 조치하였습니다.', NULL);
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 3, 8, '처리 완료', '회원이 허위 리뷰를 작성한 것이 확인되어 계정을 3일간 정지하였습니다.', 3);
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 4, 9, '처리 완료', '회원이 협박 및 위협을 한 것이 확인되어 계정을 영구 정지하였습니다.', NULL);
INSERT INTO REPORT_RESULT (REPORT_RESULT_NO, ADMIN_NO, REPORT_NO, TITLE, CONTENT, BAN_DAYS) VALUES (SEQ_REPORT_RESULT.NEXTVAL, 5, 10, '처리 완료', '기타 부적절한 행위가 발생한 것이 확인되어 경고 조치하였습니다.', NULL);
COMMIT;



-- PRODUCT_INQUIRY
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 1, 1, 1, 10, '제품 색상 문의', '이 제품의 색상은 실제로 어떤가요?');
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 2, 2, 2, 10, '배송 일정 문의', '이 제품의 배송 기간이 얼마나 걸리나요?');
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 3, 3, 3, 10, '제품 사이즈 문의', '이 제품의 사이즈는 어떻게 되나요?');
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT, PRIVATE_YN) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 4, 4, 4, 10, '재입고 문의', '이 제품의 재입고 예정이 있나요?', 'Y');
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT, PRIVATE_YN) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 5, 5, 5, 10, '제품 교환 문의', '이 제품의 교환 절차는 어떻게 되나요?', 'Y');
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 6, 6, 6, 11, '제품 사용법 문의', '이 제품의 사용법에 대해 알고 싶습니다.', '제품 사용법은 동봉된 매뉴얼을 참조해주세요.', SYSDATE);
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 7, 7, 7, 11, '제품 AS 문의', '이 제품의 AS 절차는 어떻게 되나요?', 'AS는 구매일로부터 1년 동안 무상 제공됩니다.', SYSDATE);
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 8, 8, 8, 11, '제품 소재 문의', '이 제품의 소재는 무엇인가요?', '이 제품은 100% 면으로 제작되었습니다.', SYSDATE);
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 9, 9, 9, 11, '제품 반품 문의', '이 제품의 반품 절차는 어떻게 되나요?', '반품은 구매 후 7일 이내에 가능합니다.', SYSDATE);
INSERT INTO PRODUCT_INQUIRY (PRODUCT_INQUIRY_NO, MEMBER_NO, SELLER_NO, PRODUCT_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE, PRIVATE_YN) VALUES (SEQ_PRODUCT_INQUIRY.NEXTVAL, 10, 10, 10, 11, '기타 문의', '기타 궁금한 사항이 있습니다.', '고객센터로 문의주시면 상세히 안내해드리겠습니다.', SYSDATE, 'Y');
COMMIT;


-- ORDER_INQUIRY
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 1, 1, 1, 10, '배송 상태 문의', '주문한 상품의 배송 상태는 어떻게 되나요?');
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 2, 2, 2, 10, '결제 오류 문의', '결제 과정에서 오류가 발생했습니다. 어떻게 해결할 수 있나요?');
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 3, 3, 3, 10, '주문 취소 문의', '주문을 취소하고 싶습니다. 절차가 어떻게 되나요?');
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 4, 4, 4, 10, '배송 변경 문의', '배송지를 변경하고 싶습니다. 가능한가요?');
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 5, 5, 5, 10, '추가 주문 문의', '기존 주문에 상품을 추가하고 싶습니다. 가능한가요?');
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 6, 6, 6, 11, '배송 상태 문의', '주문한 상품의 배송 상태는 어떻게 되나요?', '현재 배송 준비 중입니다. 곧 발송될 예정입니다.', SYSDATE + 3);
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 7, 7, 7, 11, '결제 오류 문의', '결제 과정에서 오류가 발생했습니다. 어떻게 해결할 수 있나요?', '결제 오류는 고객센터에 문의해주시면 신속히 해결해드리겠습니다.', SYSDATE + 2);
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 8, 8, 8, 11, '주문 취소 문의', '주문을 취소하고 싶습니다. 절차가 어떻게 되나요?', '주문 취소는 마이페이지에서 진행 가능합니다.', SYSDATE + 1);
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 9, 9, 9, 11, '배송 변경 문의', '배송지를 변경하고 싶습니다. 가능한가요?', '배송지 변경은 발송 전에만 가능합니다. 고객센터로 연락주세요.', SYSDATE + 2);
INSERT INTO ORDER_INQUIRY (ORDER_INQUIRY_NO, ORDERS_NO, MEMBER_NO, SELLER_NO, STATUS_NO, TITLE, QUESTION_CONTENT, RESPONSE_CONTENT, RESPONSE_DATE) VALUES (SEQ_ORDER_INQUIRY.NEXTVAL, 10, 10, 10, 11, '추가 주문 문의', '기존 주문에 상품을 추가하고 싶습니다. 가능한가요?', '추가 주문은 새로운 주문으로 진행해주셔야 합니다.', SYSDATE + 7);
COMMIT;