---------------------------------------
-------------- DROP -------------------
---------------------------------------
-- SEQ
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_ADDRESS;
DROP SEQUENCE SEQ_STATUS;
DROP SEQUENCE SEQ_SELLER;
DROP SEQUENCE SEQ_CATEGORY;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_COLOR;
DROP SEQUENCE SEQ_PRODUCT_SIZE;
DROP SEQUENCE SEQ_INVENTORY;
DROP SEQUENCE SEQ_PRODUCT_IMG;
DROP SEQUENCE SEQ_FAVORITE;
DROP SEQUENCE SEQ_VIEW_HISTORY;
DROP SEQUENCE SEQ_REVIEW;


-- TABLE
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE STATUS CASCADE CONSTRAINTS;
DROP TABLE SELLER CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE COLOR CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_SIZE CASCADE CONSTRAINTS;
DROP TABLE INVENTORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_IMG CASCADE CONSTRAINTS;
DROP TABLE FAVORITE CASCADE CONSTRAINTS;
DROP TABLE VIEW_HISTORY CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;

---------------------------------------
-------------- SEQ --------------------
---------------------------------------
CREATE SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_ADDRESS;
CREATE SEQUENCE SEQ_STATUS;
CREATE SEQUENCE SEQ_SELLER;
CREATE SEQUENCE SEQ_CATEGORY;
CREATE SEQUENCE SEQ_PRODUCT;
CREATE SEQUENCE SEQ_COLOR;
CREATE SEQUENCE SEQ_PRODUCT_SIZE;
CREATE SEQUENCE SEQ_INVENTORY;
CREATE SEQUENCE SEQ_PRODUCT_IMG;
CREATE SEQUENCE SEQ_FAVORITE;
CREATE SEQUENCE SEQ_VIEW_HISTORY;
CREATE SEQUENCE SEQ_REVIEW;

---------------------------------------
----------- CREATE TABLE --------------
---------------------------------------
-- MEMBER
CREATE TABLE MEMBER (
    MEMBER_NO NUMBER PRIMARY KEY
    , ID VARCHAR2(100) NOT NULL UNIQUE
    , PWD VARCHAR2(255) NOT NULL
    , NAME VARCHAR2(20) NOT NULL 
    , PHONE_NO VARCHAR2(11) NOT NULL
    , PREMIUM_YN CHAR(1) DEFAULT 'N' CHECK(PREMIUM_YN IN ('Y', 'N'))
    , DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N'))
    , CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL
    , BAN_DATE TIMESTAMP NULL
);


-- ADDRESS
CREATE TABLE ADDRESS (
    ADDRESS_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    POSTCODE VARCHAR2(10) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    DETAILED_ADDRESS VARCHAR2(200) NOT NULL,
    EXTRA_ADDRESS VARCHAR2(200),
    DEFAULT_YN CHAR(1) DEFAULT 'N' CHECK (DEFAULT_YN IN ('Y', 'N')),
    DEFAULT_REQ VARCHAR2(100) DEFAULT '조심히 와주세요~'
);


-- STATUS
CREATE TABLE STATUS (
    STATUS_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL
);

-- SELLER
CREATE TABLE SELLER (
    SELLER_NO NUMBER PRIMARY KEY,
    ACC_NAME VARCHAR2(90) NOT NULL UNIQUE,
    PWD VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK (DELETED_YN IN ('Y', 'N')) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE, 
    BANNER_IMG VARCHAR2(700) NULL,
    INFO VARCHAR2(400) NULL,
    SHIPPING_INFO VARCHAR2(200) NULL
);

-- CATEGORY
CREATE TABLE CATEGORY (
    CATEGORY_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL
);

-- PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_NO NUMBER PRIMARY KEY,
    SELLER_NO NUMBER NOT NULL,
    CATEGORY_NO NUMBER NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    DETAILS VARCHAR2(4000) NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    EDITED_DATE TIMESTAMP NULL,
    HIT NUMBER DEFAULT 0,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N')) 
);


-- COLOR
CREATE TABLE COLOR (
    COLOR_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    HEXCODE VARCHAR2(10) NOT NULL
);


-- SIZE
CREATE TABLE PRODUCT_SIZE (
    SIZE_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(10) NOT NULL UNIQUE
);


-- INVENTORY
CREATE TABLE INVENTORY (
    INVENTORY_NO NUMBER PRIMARY KEY,
    PRODUCT_NO NUMBER NOT NULL,
    COLOR_NO NUMBER NOT NULL,
    SIZE_NO NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL
);


-- PRODUCT_IMG
CREATE TABLE PRODUCT_IMG (
    IMG_NO NUMBER PRIMARY KEY,
    PRODUCT_NO NUMBER NOT NULL,
    FILENAME VARCHAR2(500) NOT NULL,
    THUMBNAIL_YN CHAR(1) DEFAULT 'N' CHECK(THUMBNAIL_YN IN ('Y', 'N')),
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N')),
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- FAVORITE
CREATE TABLE FAVORITE (
    FAVORITE_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);


-- VIEW_HISTORY
CREATE TABLE VIEW_HISTORY (
    VIEW_HIST_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    VIEW_DATE TIMESTAMP DEFAULT SYSDATE
);

-- REVIEW
CREATE TABLE REVIEW (
    REVIEW_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    PRODUCT_NO NUMBER NOT NULL,
    RATING NUMBER(10, 1) NOT NULL CHECK (RATING BETWEEN 1 AND 5 AND MOD(RATING * 10, 5) = 0),
    CONTENT VARCHAR2(2000) NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE
);

---------------------------------------
----------------- FK ------------------
---------------------------------------
-- ADDRESS - MEMBER
ALTER TABLE ADDRESS
ADD CONSTRAINT FK_ADDRESS_MEMBER_NO FOREIGN KEY (MEMBER_NO) 
REFERENCES MEMBER (MEMBER_NO);

-- PRODUCT
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_SELLER_NO FOREIGN KEY (SELLER_NO)
REFERENCES SELLER (SELLER_NO);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_CATEGORY_NO FOREIGN KEY (CATEGORY_NO)
REFERENCES CATEGORY (CATEGORY_NO);

-- INVENTORY
ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);

ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_COLOR_NO FOREIGN KEY (COLOR_NO)
REFERENCES COLOR (COLOR_NO);

ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_SIZE_NO FOREIGN KEY (SIZE_NO)
REFERENCES PRODUCT_SIZE (SIZE_NO);

-- PRODUCT_IMG
ALTER TABLE PRODUCT_IMG
ADD CONSTRAINT FK_PRODUCT_IMG_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);

-- FAVORITE
ALTER TABLE FAVORITE
ADD CONSTRAINT FK_FAVORITE_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE FAVORITE
ADD CONSTRAINT FK_FAVORITE_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);

-- VIEW_HISTORY
ALTER TABLE VIEW_HISTORY
ADD CONSTRAINT FK_VIEW_HISTORY_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE VIEW_HISTORY
ADD CONSTRAINT FK_VIEW_HISTORY_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);

-- REVIEW
ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_MEMBER_NO FOREIGN KEY (MEMBER_NO)
REFERENCES MEMBER (MEMBER_NO);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_PRODUCT_NO FOREIGN KEY (PRODUCT_NO)
REFERENCES PRODUCT (PRODUCT_NO);


---------------------------------------
------------- INSERT ------------------
---------------------------------------
-- MEMBER
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES(SEQ_MEMBER.NEXTVAL, 'USER01@gmail.com', '1234', '김태우', '01036207737');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER02@gmail.com', '1234', '이민호', '01012345678');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER03@gmail.com', '1234', '박지성', '01023456789');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER04@gmail.com', '1234', '손흥민', '01034567890');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER05@gmail.com', '1234', '김연아', '01045678901');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER06@gmail.com', '1234', '정우성', '01056789012');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER07@gmail.com', '1234', '하정우', '01067890123');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER08@gmail.com', '1234', '공유', '01078901234');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER09@gmail.com', '1234', '이영애', '01089012345');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER10@gmail.com', '1234', '배수지', '01090123456');
COMMIT;


-- ADDRESS
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 1, '10416', '기흥역로 16', '2530동 202호', '(기흥동 15번지)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 1, '12345', '강남역', '2번출구', '(3번 출구사이)'); 
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 2, '10516', '서울특별시 강남구', '삼성로 1', '(삼성동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 3, '10617', '서울특별시 강북구', '도봉로 2', '(도봉동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 4, '10718', '서울특별시 서초구', '서초로 3', '(서초동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 5, '10819', '서울특별시 송파구', '송파로 4', '(송파동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 6, '10920', '서울특별시 마포구', '마포로 5', '(마포동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 7, '11021', '서울특별시 은평구', '은평로 6', '(은평동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 8, '11122', '서울특별시 동작구', '동작로 7', '(동작동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 9, '11223', '서울특별시 강서구', '강서로 8', '(강서동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 10, '11324', '서울특별시 구로구', '구로로 9', '(구로동)');
COMMIT;


-- STATUS
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '입금/결제');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '배송준비중');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '배송중');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '배송완료');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '취소');
COMMIT;


-- SELLER
INSERT INTO SELLER(SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller01@gmail.com', '1234', '노스페이스', 'banner-img.jpg', '저희 노스페이스는 너무나 아름다운 브랜드입니다.', '노스페이스는 설 연휴간 (3/10~3/13) 배송이 되지 않습니다.');
INSERT INTO SELLER(SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller02@gmail.com', '1234', '퓨마', 'banner-img-puma.jpg', '저희 퓨마는 너무나 아름다운 브랜드입니다.');
INSERT INTO SELLER(SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller03@gmail.com', '1234', '나이키', 'banner-img.jpg', '저희 나이키는 너무나 아름다운 브랜드입니다.','나이키는 설 연휴간 (3/10~3/13) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller04@gmail.com', '1234', '아디다스', 'banner-img-adidas.jpg', '저희 아디다스는 혁신적인 브랜드입니다.', '아디다스는 명절간 (2/8~2/10) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller05@gmail.com', '1234', '리복', 'banner-img-reebok.jpg', '저희 리복은 최고의 품질을 자랑합니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller06@gmail.com', '1234', '뉴발란스', 'banner-img-newbalance.jpg', '저희 뉴발란스는 편안함을 제공합니다.', '뉴발란스는 주말간 (3/5~3/6) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller07@gmail.com', '1234', '언더아머', 'banner-img-underarmour.jpg', '저희 언더아머는 최고의 퍼포먼스를 제공합니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller08@gmail.com', '1234', '콜롬비아', 'banner-img-columbia.jpg', '저희 콜롬비아는 최고의 등산복을 제공합니다.', '콜롬비아는 명절간 (1/1~1/2) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller09@gmail.com', '1234', '빈폴', 'banner-img-beanpole.jpg', '저희 빈폴은 클래식한 패션을 제공합니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller10@gmail.com', '1234', '캘빈클라인', 'banner-img-ck.jpg', '저희 캘빈클라인은 스타일리시한 데님을 제공합니다.', '캘빈클라인은 연말연시간 (12/31~1/1) 배송이 되지 않습니다.');
COMMIT;


-- CATEGORY
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '상의');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '하의');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '모자');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '아우터');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '신발');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '스니커즈');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '가방');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '액세서리');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '기타');
COMMIT;


-- PRODUCT
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 1, 4, '노스페이스 자켓', '노스페이스 자켓 설명', 199900.99);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 2, 4, '퓨마 윈드브레이커', '윈드브레이커 냠냠구냠냠구 설명', 49900.128456789);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 3, 5, '나이키 짱짱한 운동화', '나이키 운동화 냠냠구냠냠구 냠냠구냠냠구 냠냠구냠냠구 설명', 2400900.128456789);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 1, 3, '노스페이스 모자', '노스페이스 모자 설명', 39000.25);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 2, 6, '퓨마 스니커즈', '퓨마 스니커즈 설명', 99000.40);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 3, 2, '나이키 팬츠', '나이키 팬츠 설명', 89000.60);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 4, 1, '아디다스 티셔츠', '아디다스 티셔츠 설명', 45000.99);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 4, 4, '아디다스 자켓', '아디다스 자켓 설명', 120000.50);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 5, 2, '리복 팬츠', '리복 팬츠 설명', 69000.75);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 5, 6, '리복 스니커즈', '리복 스니커즈 설명', 110000.40);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 6, 5, '뉴발란스 운동화', '뉴발란스 운동화 설명', 99000.20);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 6, 4, '뉴발란스 자켓', '뉴발란스 자켓 설명', 150000.60);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 7, 1, '언더아머 티셔츠', '언더아머 티셔츠 설명', 55000.30);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 7, 2, '언더아머 팬츠', '언더아머 팬츠 설명', 65000.50);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 8, 8, '콜롬비아 모자', '콜롬비아 모자 설명', 30000.15);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 8, 7, '콜롬비아 가방', '콜롬비아 가방 설명', 85000.45);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 9, 1, '빈폴 셔츠', '빈폴 셔츠 설명', 70000.65);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 9, 4, '빈폴 자켓', '빈폴 자켓 설명', 170000.85);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 10, 2, '캘빈클라인 팬츠', '캘빈클라인 팬츠 설명', 90000.99);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 10, 3, '캘빈클라인 모자', '캘빈클라인 모자 설명', 40000.55);
COMMIT;


-- COLOR
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '빨강', '#FF0000');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '초록', '#00FF00');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '파랑', '#0000FF');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '노랑', '#FFFF00');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '청록', '#00FFFF');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '자홍', '#FF00FF');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '검정', '#000000');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '흰색', '#FFFFFF');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '회색', '#808080');
INSERT INTO COLOR (COLOR_NO, NAME, HEXCODE) VALUES (SEQ_COLOR.NEXTVAL, '주황', '#FFA500');
COMMIT;


-- SIZE
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'S');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'M');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'L');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'XL');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'XLL');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'XLLL');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, 'FREE');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '225');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '230');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '235');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '240');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '245');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '250');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '255');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '260');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '265');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '270');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '275');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '280');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '285');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '290');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '295');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '300');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '305');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '310');
INSERT INTO PRODUCT_SIZE (SIZE_NO, NAME) VALUES (SEQ_PRODUCT_SIZE.NEXTVAL, '320');
COMMIT;

-- INVENTORY
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 1, 1, 1, 100);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 1, 2, 2, 150);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 2, 3, 3, 200);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 2, 4, 4, 250);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 3, 5, 5, 300);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 3, 6, 6, 350);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 4, 7, 7, 400);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 4, 8, 8, 450);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 5, 9, 9, 500);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 5, 10, 10, 550);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 6, 1, 11, 600);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 6, 2, 12, 650);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 7, 3, 13, 700);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 7, 4, 14, 750);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 8, 5, 15, 800);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 8, 6, 16, 850);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 9, 7, 17, 900);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 9, 8, 18, 950);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 10, 9, 19, 1000);
INSERT INTO INVENTORY (INVENTORY_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, QUANTITY) VALUES (SEQ_INVENTORY.NEXTVAL, 10, 10, 20, 1050);
COMMIT;


-- PRODUCT_IMG
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 1, 'img-1.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 1, 'img-2.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 2, 'img-3.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 2, 'img-4.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 3, 'img-5.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 3, 'img-6.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 4, 'img-7.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 4, 'img-8.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 5, 'img-9.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 5, 'img-10.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 6, 'img-11.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 6, 'img-12.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 7, 'img-13.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 7, 'img-14.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 8, 'img-15.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 8, 'img-16.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 9, 'img-17.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 9, 'img-18.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 10, 'img-19.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 10, 'img-20.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 11, 'img-21.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 11, 'img-22.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 12, 'img-23.jpg', 'Y', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 12, 'img-24.jpg', 'N', 'N');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 13, 'img-25.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 14, 'img-26.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 15, 'img-27.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 16, 'img-28.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 17, 'img-29.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 18, 'img-30.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 19, 'img-31.jpg', 'Y');
INSERT INTO PRODUCT_IMG (IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN) VALUES (SEQ_PRODUCT_IMG.NEXTVAL, 20, 'img-32.jpg', 'Y');
COMMIT;


-- FAVORITE
INSERT INTO FAVORITE(FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 1, 1, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 1, 2, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 1, 3, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 2, 4, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 2, 5, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 2, 6, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 3, 7, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 3, 8, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 3, 9, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 4, 10, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 4, 1, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 4, 2, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 5, 3, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 5, 4, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 5, 5, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 6, 6, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 6, 7, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 6, 8, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 7, 9, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 7, 10, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 7, 1, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 8, 2, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 8, 3, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 8, 4, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 9, 5, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 9, 6, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 9, 7, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 10, 8, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 10, 9, SYSDATE);
INSERT INTO FAVORITE (FAVORITE_NO, MEMBER_NO, PRODUCT_NO, CREATED_DATE) VALUES (SEQ_FAVORITE.NEXTVAL, 10, 10, SYSDATE);
COMMIT;


-- VIEW_HISTORY
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 1, 1, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 1, 2, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 1, 3, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 2, 4, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 2, 5, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 2, 6, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 3, 7, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 3, 8, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 3, 9, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 4, 10, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 4, 1, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 4, 2, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 5, 3, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 5, 4, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 5, 5, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 6, 6, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 6, 7, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 6, 8, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 7, 9, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 7, 10, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 7, 1, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 8, 2, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 8, 3, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 8, 4, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 9, 5, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 9, 6, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 9, 7, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 10, 8, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 10, 9, SYSDATE);
INSERT INTO VIEW_HISTORY (VIEW_HIST_NO, MEMBER_NO, PRODUCT_NO, VIEW_DATE) VALUES (SEQ_VIEW_HISTORY.NEXTVAL, 10, 10, SYSDATE);
COMMIT;


-- REVIEW
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 1, 1, 4.5, '정말 따뜻하고 좋아요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 1, 2, 3.5, '가볍고 편해요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 1, 3, 5.0, '최고에요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 2, 4, 4.0, '디자인이 예뻐요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 2, 5, 4.5, '너무 편해요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 2, 6, 4.0, '품질이 좋네요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 3, 7, 4.5, '강추!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 3, 8, 4.0, '아주 좋아요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 3, 9, 4.5, '아주 멋있어요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 4, 10, 4.5, '정말 편안해요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 4, 1, 4.0, '정말 따뜻하고 좋아요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 4, 2, 3.5, '가볍고 편해요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 5, 3, 5.0, '최고에요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 5, 4, 4.0, '디자인이 예뻐요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 5, 5, 4.5, '너무 편해요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 6, 6, 4.0, '품질이 좋네요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 6, 7, 4.5, '강추!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 6, 8, 4.0, '아주 좋아요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 7, 9, 4.5, '아주 멋있어요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 7, 10, 4.5, '정말 편안해요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 7, 1, 4.0, '정말 따뜻하고 좋아요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 8, 2, 3.5, '가볍고 편해요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 8, 3, 5.0, '최고에요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 8, 4, 4.0, '디자인이 예뻐요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 9, 5, 4.5, '너무 편해요!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 9, 6, 4.0, '품질이 좋네요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 9, 7, 4.5, '강추!', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 10, 8, 4.0, '아주 좋아요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 10, 9, 4.5, '아주 멋있어요.', SYSDATE);
INSERT INTO REVIEW (REVIEW_NO, MEMBER_NO, PRODUCT_NO, RATING, CONTENT, CREATED_DATE) VALUES (SEQ_REVIEW.NEXTVAL, 10, 10, 4.5, '정말 편안해요.', SYSDATE);
COMMIT;



