---------------------------------------
-------------- DROP -------------------
---------------------------------------
-- SEQ
DROP SEQUENCE SEQ_MEMBER;
DROP SEQUENCE SEQ_ADDRESS;
DROP SEQUENCE SEQ_STATUS;
DROP SEQUENCE SEQ_SELLER;
DROP SEQUENCE SEQ_CATEGORY;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_COLOR;

-- TABLE
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE STATUS CASCADE CONSTRAINTS;
DROP TABLE SELLER CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE COLOR CASCADE CONSTRAINTS;

---------------------------------------
-------------- SEQ --------------------
---------------------------------------
CREATE SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_ADDRESS;
CREATE SEQUENCE SEQ_STATUS;
CREATE SEQUENCE SEQ_SELLER;
CREATE SEQUENCE SEQ_CATEGORY;
CREATE SEQUENCE SEQ_PRODUCT;
CREATE SEQUENCE SEQ_COLOR;


---------------------------------------
----------- CREATE TABLE --------------
---------------------------------------
-- MEMBER
CREATE TABLE MEMBER (
    MEMBER_NO NUMBER PRIMARY KEY
    , ID VARCHAR2(100) NOT NULL UNIQUE
    , PWD VARCHAR2(255) NOT NULL
    , NAME VARCHAR2(20) NOT NULL 
    , PHONE_NO VARCHAR2(11) NOT NULL
    , PREMIUM_YN CHAR(1) DEFAULT 'N' CHECK(PREMIUM_YN IN ('Y', 'N'))
    , DELETED_YN CHAR(1) DEFAULT 'N' CHECK(DELETED_YN IN ('Y', 'N'))
    , CREATED_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL
    , BAN_DATE TIMESTAMP NULL
);


-- ADDRESS
CREATE TABLE ADDRESS (
    ADDRESS_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    POSTCODE VARCHAR2(10) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    DETAILED_ADDRESS VARCHAR2(200) NOT NULL,
    EXTRA_ADDRESS VARCHAR2(200),
    DEFAULT_YN CHAR(1) DEFAULT 'N' CHECK (DEFAULT_YN IN ('Y', 'N')),
    DEFAULT_REQ VARCHAR2(100) DEFAULT '조심히 와주세요~'
);


-- STATUS
CREATE TABLE STATUS (
    STATUS_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL
);

-- SELLER
CREATE TABLE SELLER (
    SELLER_NO NUMBER PRIMARY KEY,
    ACC_NAME VARCHAR2(90) NOT NULL UNIQUE,
    PWD VARCHAR2(255) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    DELETED_YN CHAR(1) DEFAULT 'N' CHECK (DELETED_YN IN ('Y', 'N')) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE, 
    BANNER_IMG VARCHAR2(700) NULL,
    INFO VARCHAR2(400) NULL,
    SHIPPING_INFO VARCHAR2(200) NULL
);

-- CATEGORY
CREATE TABLE CATEGORY (
    CATEGORY_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL
);

-- PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_NO NUMBER PRIMARY KEY,
    SELLER_NO NUMBER NOT NULL,
    CATEGORY_NO NUMBER NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    DETAILS VARCHAR2(4000) NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSDATE,
    EDITED_DATE TIMESTAMP NULL,
    HIT NUMBER DEFAULT 0,
    DELETED_YN CHAR(1) CHECK(DELETED_YN IN ('Y', 'N'))
);


-- COLOR
CREATE TABLE COLOR (
    COLOR_NO NUMBER PRIMARY KEY,
    
    
);






---------------------------------------
----------------- FK ------------------
---------------------------------------
-- ADDRESS - MEMBER
ALTER TABLE ADDRESS
ADD CONSTRAINT FK_ADDRESS_MEMBER_NO FOREIGN KEY (MEMBER_NO) 
REFERENCES MEMBER (MEMBER_NO);

-- PRODUCT
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_SELLER_NO FOREIGN KEY (SELLER_NO)
REFERENCES SELLER (SELLER_NO);

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_CATEGORY_NO FOREIGN KEY (CATEGORY_NO)
REFERENCES CATEGORY (CATEGORY_NO);




---------------------------------------
------------- INSERT ------------------
---------------------------------------
-- MEMBER
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES(SEQ_MEMBER.NEXTVAL, 'USER01@gmail.com', '1234', '김태우', '01036207737');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER02@gmail.com', '1234', '이민호', '01012345678');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER03@gmail.com', '1234', '박지성', '01023456789');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER04@gmail.com', '1234', '손흥민', '01034567890');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER05@gmail.com', '1234', '김연아', '01045678901');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER06@gmail.com', '1234', '정우성', '01056789012');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER07@gmail.com', '1234', '하정우', '01067890123');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER08@gmail.com', '1234', '공유', '01078901234');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER09@gmail.com', '1234', '이영애', '01089012345');
INSERT INTO MEMBER (MEMBER_NO, ID, PWD, NAME, PHONE_NO) VALUES (SEQ_MEMBER.NEXTVAL, 'USER10@gmail.com', '1234', '배수지', '01090123456');
COMMIT;


-- ADDRESS
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 1, '10416', '기흥역로 16', '2530동 202호', '(기흥동 15번지)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 1, '12345', '강남역', '2번출구', '(3번 출구사이)'); 
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 2, '10516', '서울특별시 강남구', '삼성로 1', '(삼성동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 3, '10617', '서울특별시 강북구', '도봉로 2', '(도봉동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 4, '10718', '서울특별시 서초구', '서초로 3', '(서초동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 5, '10819', '서울특별시 송파구', '송파로 4', '(송파동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 6, '10920', '서울특별시 마포구', '마포로 5', '(마포동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 7, '11021', '서울특별시 은평구', '은평로 6', '(은평동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 8, '11122', '서울특별시 동작구', '동작로 7', '(동작동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 9, '11223', '서울특별시 강서구', '강서로 8', '(강서동)');
INSERT INTO ADDRESS (ADDRESS_NO, MEMBER_NO, POSTCODE, ADDRESS, DETAILED_ADDRESS, EXTRA_ADDRESS) VALUES (SEQ_ADDRESS.NEXTVAL, 10, '11324', '서울특별시 구로구', '구로로 9', '(구로동)');
COMMIT;


-- STATUS
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '입금/결제');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '배송준비중');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '배송중');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '배송완료');
INSERT INTO STATUS(STATUS_NO, NAME) VALUES(SEQ_STATUS.NEXTVAL, '취소');
COMMIT;


-- SELLER
INSERT INTO SELLER(SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller01@gmail.com', '1234', '노스페이스', 'banner-img.jpg', '저희 노스페이스는 너무나 아름다운 브랜드입니다.', '노스페이스는 설 연휴간 (3/10~3/13) 배송이 되지 않습니다.');
INSERT INTO SELLER(SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller02@gmail.com', '1234', '퓨마', 'banner-img-puma.jpg', '저희 퓨마는 너무나 아름다운 브랜드입니다.');
INSERT INTO SELLER(SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller03@gmail.com', '1234', '나이키', 'banner-img.jpg', '저희 나이키는 너무나 아름다운 브랜드입니다.','나이키는 설 연휴간 (3/10~3/13) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller04@gmail.com', '1234', '아디다스', 'banner-img-adidas.jpg', '저희 아디다스는 혁신적인 브랜드입니다.', '아디다스는 명절간 (2/8~2/10) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller05@gmail.com', '1234', '리복', 'banner-img-reebok.jpg', '저희 리복은 최고의 품질을 자랑합니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller06@gmail.com', '1234', '뉴발란스', 'banner-img-newbalance.jpg', '저희 뉴발란스는 편안함을 제공합니다.', '뉴발란스는 주말간 (3/5~3/6) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller07@gmail.com', '1234', '언더아머', 'banner-img-underarmour.jpg', '저희 언더아머는 최고의 퍼포먼스를 제공합니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller08@gmail.com', '1234', '콜롬비아', 'banner-img-columbia.jpg', '저희 콜롬비아는 최고의 등산복을 제공합니다.', '콜롬비아는 명절간 (1/1~1/2) 배송이 되지 않습니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller09@gmail.com', '1234', '빈폴', 'banner-img-beanpole.jpg', '저희 빈폴은 클래식한 패션을 제공합니다.');
INSERT INTO SELLER (SELLER_NO, ACC_NAME, PWD, NAME, BANNER_IMG, INFO, SHIPPING_INFO) VALUES (SEQ_SELLER.NEXTVAL, 'seller10@gmail.com', '1234', '캘빈클라인', 'banner-img-ck.jpg', '저희 캘빈클라인은 스타일리시한 데님을 제공합니다.', '캘빈클라인은 연말연시간 (12/31~1/1) 배송이 되지 않습니다.');
COMMIT;


-- CATEGORY
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '상의');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '하의');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '모자');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '아우터');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '신발');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '스니커즈');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '가방');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '액세서리');
INSERT INTO CATEGORY(CATEGORY_NO, NAME) VALUES(SEQ_CATEGORY.NEXTVAL, '기타');
COMMIT;


-- PRODUCT
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 1, 4, '노스페이스 자켓', '노스페이스 자켓 설명', 199900.99);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 2, 4, '퓨마 윈드브레이커', '윈드브레이커 냠냠구냠냠구 설명', 49900.128456789);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 3, 5, '나이키 짱짱한 운동화', '나이키 운동화 냠냠구냠냠구 냠냠구냠냠구 냠냠구냠냠구 설명', 2400900.128456789);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 1, 3, '노스페이스 모자', '노스페이스 모자 설명', 39000.25);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 2, 6, '퓨마 스니커즈', '퓨마 스니커즈 설명', 99000.40);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 3, 2, '나이키 팬츠', '나이키 팬츠 설명', 89000.60);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 4, 1, '아디다스 티셔츠', '아디다스 티셔츠 설명', 45000.99);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 4, 4, '아디다스 자켓', '아디다스 자켓 설명', 120000.50);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 5, 2, '리복 팬츠', '리복 팬츠 설명', 69000.75);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 5, 6, '리복 스니커즈', '리복 스니커즈 설명', 110000.40);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 6, 5, '뉴발란스 운동화', '뉴발란스 운동화 설명', 99000.20);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 6, 4, '뉴발란스 자켓', '뉴발란스 자켓 설명', 150000.60);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 7, 1, '언더아머 티셔츠', '언더아머 티셔츠 설명', 55000.30);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 7, 2, '언더아머 팬츠', '언더아머 팬츠 설명', 65000.50);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 8, 8, '콜롬비아 모자', '콜롬비아 모자 설명', 30000.15);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 8, 7, '콜롬비아 가방', '콜롬비아 가방 설명', 85000.45);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 9, 1, '빈폴 셔츠', '빈폴 셔츠 설명', 70000.65);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 9, 4, '빈폴 자켓', '빈폴 자켓 설명', 170000.85);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 10, 2, '캘빈클라인 팬츠', '캘빈클라인 팬츠 설명', 90000.99);
INSERT INTO PRODUCT (PRODUCT_NO, SELLER_NO, CATEGORY_NO, NAME, DETAILS, PRICE) VALUES (SEQ_PRODUCT.NEXTVAL, 10, 3, '캘빈클라인 모자', '캘빈클라인 모자 설명', 40000.55);
COMMIT;