-- MemberDao - getMemberNo()
SELECT MEMBER_NO
FROM MEMBER
WHERE ID = 'taewookim02@gmail.com';


-- MemberDao - login()
SELECT * 
FROM MEMBER 
WHERE ID = 'taewookim02@gmail.com' 
AND PWD = '123456789A@'
AND DELETED_YN = 'N' 
AND BAN_DATE IS NULL
;




-- DECREMENT INVENTORY QUANTITY
UPDATE INVENTORY
SET QUANTITY = QUANTITY - 1
WHERE PRODUCT_NO = 1 AND COLOR_NO = 2 AND SIZE_NO = 2
;

-- HIT INCREMENT
UPDATE PRODUCT
SET HIT = HIT + 1
WHERE PRODUCT_NO = 2;



-- REVIEW 
SELECT P.NAME, M.NAME, R.CONTENT, R.RATING
FROM REVIEW R
JOIN PRODUCT P ON R.PRODUCT_NO = P.PRODUCT_NO
JOIN MEMBER M ON M.MEMBER_NO = R.MEMBER_NO
WHERE P.PRODUCT_NO = 1
;


-- ORDER DETAILS
SELECT M.NAME, P.NAME, P.PRICE, OD.QUANTITY, P.PRICE * OD.QUANTITY
FROM ORDER_DETAIL OD
JOIN ORDERS O ON OD.ORDERS_NO = O.ORDERS_NO
JOIN MEMBER M ON O.MEMBER_NO = M.MEMBER_NO
JOIN PRODUCT P ON OD.PRODUCT_NO = P.PRODUCT_NO
WHERE M.MEMBER_NO = 1
;