--------------------------------------------------------
-- 메인페이지
SELECT 
    P.PRODUCT_NO, 
    TO_CHAR(P.PRICE, '999,999,999') PRICE,  
    S.NAME SELLER_NAME,
    P.NAME PRODUCT_NAME, 
    PI.FILENAME, 
    NVL(ROUND(AVG(R.RATING), 1), 0) AVG_RATING, 
    COUNT(R.RATING) REVIEW_CNT
FROM PRODUCT P
LEFT JOIN REVIEW R ON P.PRODUCT_NO = R.PRODUCT_NO
JOIN PRODUCT_IMG PI ON P.PRODUCT_NO = PI.PRODUCT_NO
JOIN SELLER S ON P.SELLER_NO = S.SELLER_NO
WHERE PI.THUMBNAIL_YN = 'Y'
    AND P.DELETED_YN = 'N' 
    AND PI.DELETED_YN = 'N'
GROUP BY P.PRODUCT_NO, P.PRICE, S.NAME, P.NAME, PI.FILENAME
ORDER BY P.PRODUCT_NO DESC
;


--------------------------------------------------------
-- 상세페이지
-- HIT INCREMENT
UPDATE PRODUCT
SET HIT = HIT + 1
WHERE PRODUCT_NO = 2;

SELECT 
    S.NAME SELLER_NAME
    , P.NAME PRODUCT_NAME
    , TO_CHAR(P.PRICE, '999,999,999') PRICE
    , P.DETAILS DETAILS
    , P.HIT HIT
    , NVL(S.SHIPPING_INFO, '기본 배송') SHIPPING_DETAILS
    , NVL(ROUND(AVG(R.RATING), 1), 0) AVG_RATING
    , COUNT(R.REVIEW_NO) REVIEW_CNT
FROM PRODUCT P
JOIN SELLER S ON P.SELLER_NO = S.SELLER_NO
LEFT JOIN REVIEW R ON R.PRODUCT_NO = P.PRODUCT_NO
WHERE P.PRODUCT_NO = ?
GROUP BY S.NAME, P.NAME, P.PRICE, P.DETAILS, P.HIT, NVL(S.SHIPPING_INFO, '기본 배송')
;

-- /products/*
-- IMGS
SELECT IMG_NO, PRODUCT_NO, FILENAME, THUMBNAIL_YN, DELETED_YN, CREATED_DATE
FROM PRODUCT_IMG
WHERE PRODUCT_NO = ?
AND DELETED_YN = 'N'
ORDER BY THUMBNAIL_YN DESC, IMG_NO ASC
;

-- REVIEWS
SELECT R.REVIEW_NO REVIEW_NO, R.MEMBER_NO MEMBER_NO, M.NAME MEMBER_NAME, R.PRODUCT_NO, R.RATING, R.CONTENT, R.CREATED_DATE, R.DELETED_YN
FROM REVIEW R
JOIN MEMBER M ON R.MEMBER_NO = M.MEMBER_NO
WHERE R.PRODUCT_NO = 2
AND R.DELETED_YN = 'N'
ORDER BY R.REVIEW_NO DESC, R.CREATED_DATE DESC
;

SELECT 
    R.REVIEW_NO,
    R.MEMBER_NO,
    M.NAME MEMBER_NAME,
    R.PRODUCT_NO,
    R.RATING,
    R.CONTENT,
    R.CREATED_DATE,
    R.DELETED_YN,
    PS.NAME PRODUCT_SIZE,
    C.NAME PRODUCT_COLOR,
    C.HEXCODE COLOR_HEX,
    OD.QUANTITY PRODUCT_QUANTITY
FROM REVIEW R
JOIN MEMBER M ON R.MEMBER_NO = M.MEMBER_NO
JOIN ORDERS O ON R.ORDERS_NO = O.ORDERS_NO
JOIN ORDER_DETAIL OD ON O.ORDERS_NO = OD.ORDERS_NO AND R.PRODUCT_NO = OD.PRODUCT_NO
JOIN INVENTORY I ON OD.INVENTORY_NO = I.INVENTORY_NO
JOIN PRODUCT_SIZE PS ON I.SIZE_NO = PS.SIZE_NO
JOIN COLOR C ON I.COLOR_NO = C.COLOR_NO
WHERE R.PRODUCT_NO = 2
AND R.DELETED_YN = 'N'
ORDER BY R.REVIEW_NO DESC, R.CREATED_DATE DESC
;


--------------------------------------------------------
-- 랭킹페이지
SELECT 
    P.PRODUCT_NO, 
    TO_CHAR(P.PRICE, '999,999,999') PRICE,  
    S.NAME SELLER_NAME,
    P.NAME PRODUCT_NAME, 
    PI.FILENAME, 
    NVL(ROUND(AVG(R.RATING), 1), 0) AVG_RATING, 
    COUNT(R.RATING) REVIEW_CNT
FROM PRODUCT P
LEFT JOIN REVIEW R ON P.PRODUCT_NO = R.PRODUCT_NO
JOIN PRODUCT_IMG PI ON P.PRODUCT_NO = PI.PRODUCT_NO
JOIN SELLER S ON P.SELLER_NO = S.SELLER_NO
WHERE PI.THUMBNAIL_YN = 'Y'
    AND P.DELETED_YN = 'N' 
    AND PI.DELETED_YN = 'N'
GROUP BY P.PRODUCT_NO, P.PRICE, S.NAME, P.NAME, PI.FILENAME
ORDER BY AVG_RATING DESC, REVIEW_CNT DESC
;



-- MemberDao - login()
SELECT * 
FROM MEMBER 
WHERE ID = 'taewookim02@gmail.com' 
AND PWD = '123456789A@'
AND DELETED_YN = 'N' 
AND BAN_DATE IS NULL
;




-- DECREMENT INVENTORY QUANTITY
UPDATE INVENTORY
SET QUANTITY = QUANTITY - 1
WHERE PRODUCT_NO = 1 AND COLOR_NO = 2 AND SIZE_NO = 2
;





-- REVIEW 
SELECT P.NAME, M.NAME, R.CONTENT, R.RATING
FROM REVIEW R
JOIN PRODUCT P ON R.PRODUCT_NO = P.PRODUCT_NO
JOIN MEMBER M ON M.MEMBER_NO = R.MEMBER_NO
WHERE P.PRODUCT_NO = 1
;


-- ORDER DETAILS
SELECT M.NAME, P.NAME, P.PRICE, OD.QUANTITY, P.PRICE * OD.QUANTITY
FROM ORDER_DETAIL OD
JOIN ORDERS O ON OD.ORDERS_NO = O.ORDERS_NO
JOIN MEMBER M ON O.MEMBER_NO = M.MEMBER_NO
JOIN PRODUCT P ON OD.PRODUCT_NO = P.PRODUCT_NO
WHERE M.MEMBER_NO = 1
;


-- FAQ
SELECT FA.NAME, A.NICK, F.TITLE, F.CONTENT, F.HIT
FROM FAQ F
JOIN ADMIN A ON F.ADMIN_NO = A.ADMIN_NO
JOIN FAQ_CATEGORY FA ON F.FAQ_CATEGORY_NO = FA.FAQ_CATEGORY_NO;


-- REPORT - BAN